### ISSUE TITLE
無法分享單點

### ISSUE THREAD

**Issue by jidanni** [kiang/religions#3]
無法分享單點
如
![20211006T111806](https://user-images.githubusercontent.com/1230959/136135470-8793a2a3-12b2-4703-b201-5dabad2f58b6.jpg)
無法製連結，
只能分享 " https://kiang.github.io/religions/ ".

**Comment by kiang** [comment]
這有點困擾的地方是原始資料並沒有唯一 id ，而且許多廟宇的名稱是重複的，透過住址又會存在高異動性問題，也許會問問內政部能否釋出唯一編號

**Comment by jidanni** [comment]
如
https://maps.nlsc.gov.tw/goland/B/541432540000
https://lohas.taichung.gov.tw/webgis/index.html?f=landnumlocation&t=9&f=5414&n=32540000
能直接分享重點。

我也免叫人家
「先到首頁，
再輸入…
再拉…
」
等模糊分享法！

編號就暫用您內部編號就好。

**Comment by kiang** [comment]
已經加入個別網址

5517d4b11c6b254dd175193b294c651c298e5814
