### ISSUE TITLE
琉璃光寺：怎麼飛得遠？

### ISSUE THREAD

**Issue by jidanni** [kiang/religions#4]
如
```
類型	寺廟
名稱	琉璃光寺
主祀神祇	藥師佛
行政區	臺中市
地址	臺中市東勢區慶福街27-1號
教別	佛教
建別	適用監督寺廟條例寺廟
組織型態	其他
電話	04-25852622
負責人	釋傳順
WGS84X	120.863502502441
WGS84Y	24.2025508880615
```
怎麼非 [24.1963904, 120.8554330](https://www.openstreetmap.org/node/8535565751)?

**Comment by kiang** [comment]
座標以內政部提供為主，內政部沒有提供的才會透過 tgos api 查詢，目前看起來原始資料就有許多錯誤，也許跟源頭取得聯繫後看看能否一次解決

**Comment by jidanni** [comment]
反正您 27-1 座標有蠻獨特（舊？）來源！
臺中市東勢區慶福里２鄰慶福街２７之１號
https://maps.nlsc.gov.tw/
座標無誤。

**Comment by kiang** [comment]
現在看起來已經是正確的座標
https://kiang.github.io/religions/#point/%E8%87%BA%E4%B8%AD%E5%B8%82/88eb040d-4ff7-4b17-b1fc-181343e07693
