### ISSUE TITLE
未標台中新社慈后宮

### ISSUE THREAD

**Issue by jidanni** [kiang/religions#5]
如台中新社[慈后宮](https://www.openstreetmap.org/way/508175117)
現場很壯觀，
惟圖沒標示。

**Comment by kiang** [comment]
現在看起來有這個資料了
https://kiang.github.io/religions/#point/%E8%87%BA%E4%B8%AD%E5%B8%82/bae54365-0b26-433b-b899-9ed9e9e0f692
